FROM alpine/git AS source
RUN git clone --depth 1 --branch develop https://github.com/adsxaluangit/edumaster.git /src

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=source /src/edumaster-frontend/package.json ./
RUN npm install
COPY --from=source /src/edumaster-frontend .
RUN npm run build

FROM nginx:alpine
COPY --from=source /src/edumaster-frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
